output: table
repos:
  - url: https://github.com/26huitailang/yogo.git
    branchs: [main, dev]
    authors:
      - name: 26huitailang
        alias: [peterChen]
    pathspec:
      - "*.go"
      - "!framework"
      - "!vendor"
