authors:
  - name: 26huitailang
    alias: [peterChen, ChenSJ]
repos:
  - url: https://github.com/26huitailang/yogo.git
    branches: [main, dev]
    username:
    password:
    pathspec: # !exclude 要写到前面
      - "!framework"
      - "!vendor"
      - "*.go"
  - url: https://gitlab.com/26huitailang/test-git-stat.git
    branches: [main, dev]
    pathspec:
      - "*.md"
      - "*.go"
  - url: https://github.com/26huitailang/git-stat.git
    branches: [main]
    pathspec:
      - "*.rs"
