[package]
name = "git"
version = "0.1.0"
edition = "2021"

[dependencies]
git2 = "0.19.0"
chrono.workspace = true
log.workspace = true
serde.workspace = true
config = { path = "../config"}
csv.workspace = true
clap.workspace = true

[lib]
path = "lib.rs"